### ISSUE TITLE
Error when I enter: python -m src.gradio.gradio_app

### ISSUE THREAD

**Issue by MarsEverythingTech** [Yuanshi9815/OminiControl#26]
Hello,

I followed the installation steps provided, but I got this error when I enter: python -m src.gradio.gradio_app

(omini) C:\OminiControl>python -m src.gradio.gradio_app
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\utils\import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\models\clip\modeling_clip.py", line 28, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\modeling_utils.py", line 59, in <module>
    from .quantizers import AutoHfQuantizer, HfQuantizer
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\quantizers\__init__.py", line 14, in <module>
    from .auto import AutoHfQuantizer, AutoQuantizationConfig
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\quantizers\auto.py", line 44, in <module>
    from .quantizer_torchao import TorchAoHfQuantizer
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\quantizers\quantizer_torchao.py", line 35, in <module>
    from torchao.quantization import quantize_
ImportError: cannot import name 'quantize_' from 'torchao.quantization' (C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\torchao\quantization\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\diffusers\pipelines\flux\pipeline_flux.py", line 20, in <module>
    from transformers import CLIPTextModel, CLIPTokenizer, T5EncoderModel, T5TokenizerFast
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\utils\import_utils.py", line 1767, in __getattr__
    value = getattr(module, name)
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\utils\import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\transformers\utils\import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
cannot import name 'quantize_' from 'torchao.quantization' (C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\torchao\quantization\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\OminiControl\src\gradio\gradio_app.py", line 4, in <module>
    from diffusers.pipelines import FluxPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\diffusers\utils\import_utils.py", line 844, in __getattr__
    value = getattr(module, name)
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.flux.pipeline_flux because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
cannot import name 'quantize_' from 'torchao.quantization' (C:\Users\AppData\Local\Programs\Miniconda3\envs\omini\lib\site-packages\torchao\quantization\__init__.py)

How can I fix it?
Thanks in advance.

**Comment by Yuanshi9815** [comment]
Hi @MarsEverythingTech ,

You can try this to fix the problem.
```
pip install torchao --upgrade.
```

**Comment by MarsEverythingTech** [comment]
> Hi @MarsEverythingTech ,
> 
> You can try this to fix the problem.
> 
> ```
> pip install torchao --upgrade.
> ```

I have tried this, but unfortunately, it didn't fix it.

**Comment by melanie0901** [comment]
same problem, plz help!

**Comment by Yuanshi9815** [comment]
I'm sorry to hear about this issue. Since I don't have access to a Windows environment to reproduce this bug, I can't test it directly. However, I found some similar issues reported—this appears to be a HuggingFace-related problem.

You may find helpful information in this discussion thread:
https://discuss.huggingface.co/t/loading-flux-from-local-safetensors/117488/14

**Comment by kurttu4** [comment]
torchao 0.4.0 https://github.com/pytorch/ao/releases/tag/v0.4.0
pip install torch==2.4.1+cu124

**Comment by MarsEverythingTech** [comment]
> torchao 0.4.0 https://github.com/pytorch/ao/releases/tag/v0.4.0 pip install torch==2.4.1+cu124

I didn't understand. what do I need to enter into CMD?

**Comment by Zengrath** [comment]
I also have this problem

**Comment by halilugur** [comment]
I have different trace:

Traceback (most recent call last):
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/halilugur/OminiControl/src/gradio/gradio_app.py", line 112, in <module>
    init_pipeline()
  File "/home/halilugur/OminiControl/src/gradio/gradio_app.py", line 22, in init_pipeline
    transformer_model = FluxTransformer2DModel.from_pretrained(
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 929, in from_pretrained
    raise e
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/accelerate/big_modeling.py", line 617, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1932, in load_checkpoint_in_model
    loaded_checkpoint = load_state_dict(checkpoint_file, device_map=device_map)
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1724, in load_state_dict
    return torch.load(checkpoint_file, map_location=torch.device("cpu"))
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/torch/serialization.py", line 1360, in load
    return _load(
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/torch/serialization.py", line 1848, in _load
    result = unpickler.load()
  File "/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/torch/serialization.py", line 1837, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'PlainAQTLayout' on <module 'torchao.dtypes.affine_quantized_tensor' from '/home/halilugur/miniconda3/envs/omini/lib/python3.10/site-packages/torchao/dtypes/affine_quantized_tensor.py'>
